"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.possessions = exports.Possession = exports.actions = exports.Action = void 0;
var Action_1 = require("./Action");
Object.defineProperty(exports, "Action", { enumerable: true, get: function () { return Action_1.Action; } });
var Possession_1 = require("./Possession");
Object.defineProperty(exports, "Possession", { enumerable: true, get: function () { return Possession_1.Possession; } });
var actions = Object.keys(Action_1.Action).map(function (k) { return Action_1.Action[k]; });
exports.actions = actions;
var possessions = Object.keys(Possession_1.Possession).map(function (k) { return Possession_1.Possession[k]; });
exports.possessions = possessions;
